server:
  port: 9000
spring:
  application:
    name: l-mix-cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost
    gateway:
      routes:
        - id: l-mix-admin-route
          uri: lb://l-mix-cloud-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: l-mix-api-route
          uri: lb://l-mix-cloud-api
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: l-mix-auth-route
          uri: lb://l-mix-cloud-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能
          lower-case-service-id: true # 使用小写服务名，默认是大写
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9001/rsa/publicKey' # 配置RSA的公钥访问地址
# 自定义配置
lmix:
  secure:
    ignore:
      uris: # 配置白名单路径
        - "/auth/oauth/token"
        - "/actuator/**"
        - "/api/public/**"
    auth_url_roles:
      - uri: "/admin/user/adminInfo"
        roles: ["ADMIN"]
      - uri: "/admin/user/currentUser"
        roles: ["ADMIN","USER"]