spring:
  application:
    name: l-mix-common-data
  datasource:
    url: jdbc:mysql://localhost:3306/lmix?serverTimezone=GMT%2B8&useSSL=true&useUnicode=true&characterEncoding=utf8
    username: lmix
    password: lmix
    driver-class-name: com.mysql.cj.jdbc.Driver