spring:
  application:
    name: l-mix-common-data
  datasource:
    url: jdbc:mysql://localhost:3306/lmix
    username: lmix
    password: lmix
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    port: 6379
    host: localhost
    password: